export const fontFamilyPretendard = "'Pretendard', sans-serif";

export const fontWeightRegular = 400;
export const fontWeightMedium = 500;
export const fontWeightSemibold = 600;
export const fontWeightBold = 700;

export const typography = {
  'headline1-bold': {
    fontSize: 44,
    lineHeight: 52,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline1-semibold': {
    fontSize: 44,
    lineHeight: 52,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline1-medium': {
    fontSize: 44,
    lineHeight: 52,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline1-regular': {
    fontSize: 44,
    lineHeight: 52,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-bold': {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-semibold': {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-medium': {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-regular': {
    fontSize: 40,
    lineHeight: 48,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-bold': {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-semibold': {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-medium': {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-regular': {
    fontSize: 32,
    lineHeight: 40,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-bold': {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-semibold': {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-medium': {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-regular': {
    fontSize: 28,
    lineHeight: 36,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-bold': {
    fontSize: 16,
    lineHeight: 26,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-semibold': {
    fontSize: 16,
    lineHeight: 26,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-medium': {
    fontSize: 16,
    lineHeight: 26,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-regular': {
    fontSize: 16,
    lineHeight: 26,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-bold': {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-semibold': {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-medium': {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-regular': {
    fontSize: 14,
    lineHeight: 22,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-bold': {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-semibold': {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-medium': {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-regular': {
    fontSize: 12,
    lineHeight: 18,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
}