export const fontFamilyPretendard = "'Pretendard', sans-serif";

export const fontWeightRegular = 400;
export const fontWeightMedium = 500;
export const fontWeightSemibold = 600;
export const fontWeightBold = 700;

export const typography = {
  'display2-bold': {
    fontSize: 64,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'display2-semibold': {
    fontSize: 64,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'display2-medium': {
    fontSize: 64,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'display2-regular': {
    fontSize: 64,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline1-bold': {
    fontSize: 44,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline1-semibold': {
    fontSize: 44,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline1-medium': {
    fontSize: 44,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline1-regular': {
    fontSize: 44,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-bold': {
    fontSize: 40,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-semibold': {
    fontSize: 40,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-medium': {
    fontSize: 40,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline2-regular': {
    fontSize: 40,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-bold': {
    fontSize: 32,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-semibold': {
    fontSize: 32,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-medium': {
    fontSize: 32,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline3-regular': {
    fontSize: 32,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-bold': {
    fontSize: 28,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-semibold': {
    fontSize: 28,
          lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-medium': {
    fontSize: 28,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'headline4-regular': {
    fontSize: 28,
        lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'title2-bold': {
    fontSize: 20,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'title2-semibold': {
    fontSize: 20,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'title2-medium': {
    fontSize: 20,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'title2-regular': {
    fontSize: 20,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-bold': {
    fontSize: 16,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-semibold': {
    fontSize: 16,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-medium': {
    fontSize: 16,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'body-regular': {
    fontSize: 16,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-bold': {
    fontSize: 14,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-semibold': {
    fontSize: 14,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-medium': {
    fontSize: 14,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption1-regular': {
    fontSize: 14,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-bold': {
    fontSize: 12,
    lineHeight: 100,
    fontWeight: fontWeightBold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-semibold': {
    fontSize: 12,
    lineHeight: 100,
    fontWeight: fontWeightSemibold,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-medium': {
    fontSize: 12,
    lineHeight: 100,
    fontWeight: fontWeightMedium,
    letterSpacing: "normal",
    textDecoration: "none",
  },
  'caption2-regular': {
    fontSize: 12,
    lineHeight: 100,
    fontWeight: fontWeightRegular,
    letterSpacing: "normal",
    textDecoration: "none",
  },
}